# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'catppuccin/tmux#v2.3.0'

# Catppuccin
set -g @catppuccin_flavor 'macchiato'
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_window_default_text "#W"

# Colors
set -g @ctp_bg "#24273a"
set -g @ctp_surface_1 "#494d64"
set -g @ctp_fg "#cad3f5"
set -g @ctp_mauve "#c6a0f6"
set -g @ctp_crust "#181926"

# Status line
set -g status-left-length 100
set -g status-right-length 100
set -g status-left ""
set -gF status-style "bg=#{@ctp_bg},fg=#{@ctp_fg}"
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_ram}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"
set -g extended-keys on

# Windows
set -g renumber-windows on
set -g base-index 1
set -g automatic-rename off
set -g allow-rename off

# General
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -ga update-environment "COLORTERM"
#set -ga terminal-overrides ",*256col*:Tc"
set -g history-limit 15000
set -sg escape-time 1
set -g visual-activity off
set -g monitor-activity on
setw -g monitor-activity on
set -g mouse on
set -g status-interval 10

# Prefix
unbind C-b
set -g prefix `
bind ` send-prefix

# Navigation
setw -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind v split-window -v
bind b split-window -h
bind r source ~/.tmux.conf \; display '~/.tmux.conf sourced'

# Copy mode
bind Enter copy-mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi Escape send -X cancel
bind -T copy-mode-vi L send -X end-of-line
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

# TPM (keep at bottom)
run '~/.tmux/plugins/tpm/tpm'
set -g window-status-activity-style "fg=#f5a97f"  # e.g. peach color for activity
set -g window-status-format "#[fg=#181926,bg=#{@thm_overlay_2}] #[fg=#1e2030,reverse]#[none]#I #[fg=#cad3f5,bg=#{@thm_surface_0}] #W#[fg=#1e2030,reverse]#[none]"
set -g window-status-separator "  "
set -g window-status-current-format "#[fg=#181926,bg=#{@thm_mauve}] #I #[fg=#cad3f5,bold,bg=#{@thm_surface_1}] #W "

